services:
  db:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auction_logs
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
